site_name: Linux运维与DevOps实战_学习笔记
repo_url: https://github.com/jlice/shiyanlou-linux
site_description: 《Linux运维与DevOps实战》学习笔记
site_author: 文剑木然

# extra_javascript: 
#     - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# markdown_extensions:
#     - mdx_math

theme: 
    name: material
    font: false
extra_css: 
    - extra.css
    
pages: 
    - 主页: index.md
    - Linux基础: 
        - 'Linux 简介与使用': 'week01/Linux简介与使用.md'
        - 'Linux 基本操作': 'week01/Linux基本操作.md'
        - 'Linux 用户与权限': 'week01/Linux用户与权限.md'
        - 'Linux 目录与文件': 'week01/Linux目录与文件.md'
        - 'Linux 文件查找与打包': 'week01/Linux文件查找与打包.md'
        - 'Linux 文本编辑': 'week01/Linux文本编辑.md'
        - 'Linux 管道符': 'week01/Linux管道符.md'
        - 'Linux 磁盘管理': 'week01/Linux磁盘管理.md'
        - 'Linux 系统备份与恢复': 'week01/Linux系统备份与恢复.md'
        - 'Linux 任务计划': 'week01/Linux任务计划.md'
        - 'Linux 软件管理': 'week01/Linux软件管理.md'
        - 'Linux 启动流程': 'week01/Linux启动流程.md'
        - 'Linux 进程与工作': 'week01/Linux进程与工作.md'
        - 'Linux 帮助命令': 'week01/Linux帮助命令.md'
        - 'Linux 日志系统': 'week01/Linux日志系统.md'
    - Shell编程与文本处理: 
        - 'Bash 入门': 'week02/Bash入门.md'
        - 'Bash 变量': 'week02/Bash变量.md'
        - 'Bash 基本运算': 'week02/Bash基本运算.md'
        - 'Bash 流程控制': 'week02/Bash流程控制.md'
        - 'Bash 函数和数组': 'week02/Bash函数和数组.md'
        - 'Bash 正则表达式': 'week02/Bash正则表达式.md'
        - '高级 Sed 使用': 'week02/高级Sed使用.md'
        - 'awk 入门': 'week02/awk入门.md'
        - 'awk 流程控制': 'week02/awk流程控制.md'
        - 'awk 函数': 'week02/awk函数.md'
    - Linux防火墙与安全: 
        - 'TCP/IP 简介': 'week03/TCP_IP简介.md'
        - 'Socket 简介': 'week03/Socket简介.md'
        - '网络常用命令': 'week03/网络常用命令.md'
        - '防火墙介绍': 'week03/防火墙介绍.md'
        - 'TCP wrappers': 'week03/TCP_wrappers.md'
        - '初学 iptables': 'week03/初学iptables.md'
        - 'iptables 攻击防御': 'week03/iptables攻击防御.md'
        - 'iptables 脚本实例': 'week03/iptables脚本实例.md'
        - 'SELinux 简介': 'week03/SELinux简介.md'
        - 'SELinux 策略与规则管理': 'week03/SELinux策略与规则管理.md'
        # - 'SELinux 应用实例': 'week03/SELinux应用实例.md'
    - Linux网络服务部署: 
        - 'Linux DHCP 服务部署与配置': 'week04/Linux_DHCP服务部署与配置.md'
        # - 'Linux DNS 服务部署与配置': 'week04/LinuxDNS服务部署与配置.md'
        - 'Linux FTP 服务部署与配置': 'week04/Linux_FTP服务部署与配置.md'
        - 'Linux Samba 服务部署与配置': 'week04/Linux_Samba服务部署与配置.md'
        # - 'Linux 邮件服务部署与配置': 'week04/Linux邮件服务部署与配置.md'
        # - 'Linux VPN 服务部署与配置': 'week04/LinuxVPN服务部署与配置.md'
        # - 'Linux SSH 服务部署与配置': 'week04/LinuxSSH服务部署与配置.md'
        # - 'Linux NFS 服务部署与配置': 'week04/LinuxNFS服务部署与配置.md'
    # - Python 基础: 
        # - 'Python 基础语法': 'week05/Python基础语法.md'
        # - '列表、元组、集合与字典': 'week05/列表、元组、集合与字典.md'
        # - '函数': 'week05/函数.md'
        # - '面向对象编程': 'week05/面向对象编程.md'
        # - '文件处理': 'week05/文件处理.md'
        # - 'Python 高级特性': 'week05/Python高级特性.md'
        # - 'Python 多进程与多线程': 'week05/Python多进程与多线程.md'
        # - '常用模块': 'week05/常用模块.md'
    - 系统监控技术: 
        - 'Linux 系统监控常用命令': 'week06/Linux系统监控常用命令.md'
        # - 'Python 监控脚本': 'week06/Python监控脚本.md'
        # - 'Nagios 监控平台搭建': 'week06/Nagios监控平台搭建.md'
        # - 'Nagios 配置': 'week06/Nagios配置.md'
        # - 'Nagios 监控 Linux 主机': 'week06/Nagios监控Linux主机.md'
        # - 'Nagios 监控 Mysql 服务': 'week06/Nagios监控Mysql服务.md'
        # - 'Zabbix 监控平台搭建': 'week06/Zabbix监控平台搭建.md'
        # - 'Zabbix 简单配置': 'week06/Zabbix简单配置.md'
        # - 'Zabbix 自定义模板': 'week06/Zabbix自定义模板.md'
        # - 'Zabbix 报警配置': 'week06/Zabbix报警配置.md'
        # - 'Zabbix 监控 Nginx': 'week06/Zabbix监控Nginx.md'
    - 数据库运维: 
        - 'SQL 与 MYSQL': 'week07/SQL与MYSQL.md'
        - '数据库的简单操作': 'week07/数据库的简单操作.md'
        - 'MySQL 语言结构和数据类型': 'week07/MySQL语言结构和数据类型.md'
        # - '数据表的简单操作': 'week07/数据表的简单操作.md'
        # - '修改数据表定义': 'week07/修改数据表定义.md'
        # - '数据的搜索': 'week07/数据的搜索.md'
        # - '数据表的联结与视图': 'week07/数据表的联结与视图.md'
        # - '用户数据与课程数据的统计': 'week07/用户数据与课程数据的统计.md'
        # - '事务': 'week07/事务.md'
        # - 'SQL 高级特性': 'week07/SQL高级特性.md'
        # - 'MySQL 的权限和账户管理': 'week07/MySQL的权限和账户管理.md'
        # - '让数据库更加安全': 'week07/让数据库更加安全.md'
        # - 'MySQL 备份与恢复': 'week07/MySQL备份与恢复.md'
        # - '导入数据内容': 'week07/导入数据内容.md'
        # - 'MongoDB 简介与安装': 'week07/MongoDB简介与安装.md'
        # - 'MongoDB 基本操作': 'week07/MongoDB基本操作.md'
        # - 'MongoDB 导入导出': 'week07/MongoDB导入导出.md'
        # - 'Redis 简介与安装': 'week07/Redis简介与安装.md'
        # - 'Redis 数据类型': 'week07/Redis数据类型.md'
        # - 'Redis 常用配置应用': 'week07/Redis常用配置应用.md'
    - Linux集群运维: 
        - 'LVS 简介': 'week08/LVS简介.md'
        - 'LVS 实战': 'week08/LVS实战.md'
        # - '创建高可用的实验楼': 'week08/创建高可用的实验楼.md'
        # - 'Keepalived 原理与工作机制': 'week08/Keepalived原理与工作机制.md'
        # - 'LVS + Keepalived 搭建高可用集群': 'week08/LVS+Keepalived搭建高可用集群.md'
        # - '解决实验楼单点隐患': 'week08/解决实验楼单点隐患.md'
        # - 'HAProxy 搭建高可用负载系统': 'week08/HAProxy搭建高可用负载系统.md'
        # - '模块拆分，请求分发': 'week08/模块拆分，请求分发.md'
        # - 'Squid 搭建代理服务器': 'week08/Squid搭建代理服务器.md'
        # - '为非会员用户开放源地址': 'week08/为非会员用户开放源地址.md'
    - Web服务运维: 
        - 'Apache 配置入门': 'week09/Apache配置入门.md'
        # - '测试新项目': 'week09/测试新项目.md'
        # - 'Nginx 配置入门': 'week09/Nginx配置入门.md'
        # - '让实验楼网站恢复访问': 'week09/让实验楼网站恢复访问.md'
        # - 'ELK(R) 环境搭建': 'week09/ELK(R)环境搭建.md'
        # - '优化 ELK 配置': 'week09/优化ELK配置.md'
        # - 'Logstash 配置': 'week09/Logstash配置.md'
        # - '分析 Nginx 日志': 'week09/分析Nginx日志.md'
        # - 'Kibana 数据可视化': 'week09/Kibana数据可视化.md'
        # - 'Redis 与 ELK': 'week09/Redis与ELK.md'
        # - 'Filebeat 与 ELK': 'week09/Filebeat与ELK.md'
        # - '让我们的 ELK 更轻便': 'week09/让我们的ELK更轻便.md'
    # - 自动化运维: 
        # - 'Ansible 初试': 'week10/Ansible初试.md'
        # - '找出错误机器名的服务器': 'week10/找出错误机器名的服务器.md'
        # - 'Playbook 实战': 'week10/Playbook实战.md'
        # - '修复所有机器名': 'week10/修复所有机器名.md'
        # - 'Ansible 调试': 'week10/Ansible调试.md'
        # - 'Saltstack 安装与配置': 'week10/Saltstack安装与配置.md'
        # - 'Saltstack 基础应用': 'week10/Saltstack基础应用.md'
        # - '获取所有Saltstack minion的IP地址': 'week10/获取所有Saltstackminion的IP地址.md'
        # - 'Saltstack 实战': 'week10/Saltstack实战.md'
        # - '使用 Saltstack 部署 Apache': 'week10/使用Saltstack部署Apache.md'
        # - 'Supervisor 安装与配置': 'week10/Supervisor安装与配置.md'
        # - '让 Supervisord 监管 apache2': 'week10/让Supervisord监管apache2.md'
    - Devops实践: 
        # - 'Docker 概念与安装': 'week11/Docker概念与安装.md'
        - 'Docker 容器与镜像管理': 'week11/Docker容器与镜像管理.md'
        # - '通过 Docker 运行一个 MySQL 服务': 'week11/通过Docker运行一个MySQL服务.md'
        # - 'Docker 存储与网络': 'week11/Docker存储与网络.md'
        # - '通过 iptables 更新容器端口映射': 'week11/通过iptables更新容器端口映射.md'
        # - 'Dockerfile与Docker Compose': 'week11/Dockerfile与DockerCompose.md'
        # - 'Docker Swarm': 'week11/DockerSwarm.md'
        # - 'Jenkins 构建 CI,CD': 'week11/Jenkins构建CI,CD.md'
        # - 'Jenkinsfile 编写': 'week11/Jenkinsfile编写.md'
        # - 'Git+Docker多环境自动部署': 'week11/Git+Docker多环境自动部署.md'
    # - 云计算技术: 
        # - '虚拟化技术与 Libvirt 接口': 'week12/虚拟化技术与Libvirt接口.md'
        # - 'Openstack 私有云安装部署': 'week12/Openstack私有云安装部署.md'
        # - 'OpenStack 身份认证服务': 'week12/OpenStack身份认证服务.md'
        # - 'OpenStack 镜像服务': 'week12/OpenStack镜像服务.md'
        # - 'OpenStack 对象存储': 'week12/OpenStack对象存储.md'
        # - 'OSS 搭建本地文件系统': 'week12/OSS搭建本地文件系统.md'
        # - '快速搭建 RDS 关系型数据库': 'week12/快速搭建RDS关系型数据库.md'
        # - 'RDS 与 ECS 自建数据库的主从复制': 'week12/RDS与ECS自建数据库的主从复制.md'
        # - 'RDS 的数据备份与恢复': 'week12/RDS的数据备份与恢复.md'
        # - 'SLB 负载均衡使用教程': 'week12/SLB负载均衡使用教程.md'
        # - '基于VPC搭建ECS负载均衡服务': 'week12/基于VPC搭建ECS负载均衡服务.md'
    # - Web安全实战: 
        # - 'Web 渗透测试实验说明': 'week13/Web渗透测试实验说明.md'
        # - '发现 Web 漏洞的方法': 'week13/发现Web漏洞的方法.md'
        # - 'BeEF 攻击实战': 'week13/BeEF攻击实战.md'
        # - '反射型跨站脚本（XSS）攻击': 'week13/反射型跨站脚本（XSS）攻击.md'
        # - '存储型跨站脚本（XSS）攻击': 'week13/存储型跨站脚本（XSS）攻击.md'
        # - 'SQL 注入': 'week13/SQL注入.md'
        # - 'SQL注入（Blind）': 'week13/SQL注入（Blind）.md'
        # - '本地文件包含': 'week13/本地文件包含.md'
        # - '远程文件包含': 'week13/远程文件包含.md'
        # - 'Metasploit 渗透攻击 Web 服务': 'week13/Metasploit渗透攻击Web服务.md'
        # - 'Web 弱密码暴力破解': 'week13/Web弱密码暴力破解.md'
        # - '跨站请求伪造（CSRF）': 'week13/跨站请求伪造（CSRF）.md'
        # - '命令注入攻击': 'week13/命令注入攻击.md'
        # - '验证码安全问题': 'week13/验证码安全问题.md'
        # - '拒绝服务攻击（Dos）': 'week13/拒绝服务攻击（Dos）.md'
        # - 'Ajax 安全问题': 'week13/Ajax安全问题.md'
        # - 'Web 会话劫持': 'week13/Web会话劫持.md'
        # - '使用 Metasploit 攻击 IE 浏览器漏洞': 'week13/使用Metasploit攻击IE浏览器漏洞.md'
        # - 'WebShell 访问后门': 'week13/WebShell访问后门.md'
        # - '如何避免 Web 安全漏洞': 'week13/如何避免Web安全漏洞.md'
    - 服务器安全实战: 
        - 'Kali 实验环境介绍与使用': 'week14/Kali实验环境介绍与使用.md'
        # - '一次简单的渗透测试实战': 'week14/一次简单的渗透测试实战.md'
        # - '使用多种安全工具获取目标主机信息': 'week14/使用多种安全工具获取目标主机信息.md'
        # - 'Metasploit 基础知识和使用': 'week14/Metasploit基础知识和使用.md'
        # - 'Nmap 配合 Metasploit 进行端口扫描': 'week14/Nmap配合Metasploit进行端口扫描.md'
        # - '扫描目标主机网络服务安全漏洞': 'week14/扫描目标主机网络服务安全漏洞.md'
        # - 'Kali 常用漏洞扫描工具实战': 'week14/Kali常用漏洞扫描工具实战.md'
        # - '开发新的 Metasploit 扫描器': 'week14/开发新的Metasploit扫描器.md'
        # - '攻击 Ingreslock 后门漏洞': 'week14/攻击Ingreslock后门漏洞.md'
        # - 'Samba 漏洞攻击 Linux 服务器': 'week14/Samba漏洞攻击Linux服务器.md'
        # - '攻击 Unreal Ircd 服务': 'week14/攻击UnrealIrcd服务.md'
        # - '暴力破解 SSH 及 VNC 远程连接': 'week14/暴力破解SSH及VNC远程连接.md'
        # - '攻击 Distcc 获取权限': 'week14/攻击Distcc获取权限.md'
        # - '目标 Linux 服务器提权': 'week14/目标Linux服务器提权.md'
        # - '攻击 Tomcat 服务漏洞': 'week14/攻击Tomcat服务漏洞.md'
        # - '利用 NFS 错误配置进行攻击': 'week14/利用NFS错误配置进行攻击.md'
        # - '利用 FTP 服务漏洞进行攻击': 'week14/利用FTP服务漏洞进行攻击.md'
        # - '利用 Telnet 服务漏洞进行攻击': 'week14/利用Telnet服务漏洞进行攻击.md'
        # - '创建包含 Windows 后门的 PDF 文件': 'week14/创建包含Windows后门的PDF文件.md'
        # - '攻击后清除痕迹并创建访问后门': 'week14/攻击后清除痕迹并创建访问后门.md'
